### ISSUE TITLE
Definição do controle de acesso

### ISSUE THREAD

**Issue by alexandrearaujo** [alexandrearaujo/modulo#36]

**Comment by alexandrearaujo** [comment]
- [ ] Autenticação com CAS.
- [ ] Menu.
- [ ] Autorização.
- [ ] Adequeção a estrutura de Ação da MV.
- [ ] Definição e Criação de nova estrutura?
- [ ] Necessidade de migração dos dados?
- [ ] Testes.
- [ ] Documentação.

**Comment by fernandoGN** [comment]
- [ ] Remover autenticação do módulo.
