### ISSUE TITLE
Refatorar Componentes para ingles

### ISSUE THREAD

**Issue by alexandrearaujo** [alexandrearaujo/modulo#39]

**Comment by alexandrearaujo** [comment]
Altera nome dos parametros e tudo que estiver em portugues para ingles.

**Comment by fernandoGN** [comment]
Fazendo em paralelo com as atividades: #43, #41;

**Comment by fernandoGN** [comment]
- [x]  input
- [ ]  temporal
- [ ]  selectable
- [ ]  bar
- [ ]  message

**Comment by fernandoGN** [comment]
- [x]  input
- [ ]  temporal
- [ ]  selectable
- [ ]  bar
- [ ]  message

**Comment by fernandoGN** [comment]
Comitando...
