### ISSUE TITLE
Padronização da nomenclatura dos atributos dos componentes do front-end

### ISSUE THREAD

**Issue by alexandrearaujo** [alexandrearaujo/modulo#41]

**Comment by alexandrearaujo** [comment]
Padronizar os atributos dos componentes. 
Ex: idComponente, IdField.

**Comment by fernandoGN** [comment]
Fazendo em paralelo com as atividades: #43, #39;

**Comment by fernandoGN** [comment]
- [x]  input
- [ ]  temporal
- [ ]  selectable
- [ ]  bar
- [ ]  message

**Comment by fernandoGN** [comment]
Comitando...
