### ISSUE TITLE
Rever a div Label dos componentes

### ISSUE THREAD

**Issue by alexandrearaujo** [alexandrearaujo/modulo#43]

**Comment by alexandrearaujo** [comment]
<div>
			<label th:if="${idField}" class="control-label" th:classappend="${required} ? 'required' : ''" th:for="${nameField}" th:id="__${idField}__+Label">
				<span th:text="#{${label}}"></span>
			</label>
			
			<label th:unless="${idField}" class="control-label" th:classappend="${required} ? 'required' : ''" th:for="${nameField}">
				<span th:text="#{${label}}"></span>
			</label>
		</div>

**Comment by fernandoGN** [comment]
Fazendo em paralelo com as atividades: #41, #39;

**Comment by fernandoGN** [comment]
- []  temporal
- []  selectable
- []  input
- []  bar
- []  message

**Comment by fernandoGN** [comment]
Vamos deixar só a primeira label e iremos obrigar a usar o idField e o Label.

**Comment by fernandoGN** [comment]
Comitando...
