### ISSUE TITLE
Criar componente de paginação semelhante ao da MV

### ISSUE THREAD

**Issue by fernandoGN** [alexandrearaujo/modulo#45]
Nosso componente de paginação atual gera problema quando temos muitas páginas. O que tende a ocorrer em cruds tipo o cidadão.

**Comment by alexandrearaujo** [comment]
Restringir número de páginas

**Comment by fernandoGN** [comment]
Iniciando task.

**Comment by fernandoGN** [comment]
Vou fazer a paginação usando os ... para indicar que existe mais página além das mostradas atualmente.
