### ISSUE TITLE
Problema em requisiçõeso $.post para o spring

### ISSUE THREAD

**Issue by fernandoGN** [alexandrearaujo/modulo#58]
Foi constatado que nos últimos projeto o spring não está reconhecendo os parâmetros enviados por requisições post via ajax. O estranho é que na primeira versão do dispensação isso era rotineiro e funcionava muito bem.

No momento os parâmetros nas requisições $.get estão passando com tranquilidade.

**Comment by alexandrearaujo** [comment]
- http://stackoverflow.com/questions/3983556/using-jquery-to-post-json-object-to-spring-3-controller
