### ISSUE TITLE
AutoConvert para tipos DATE no Spring

### ISSUE THREAD

**Issue by fernandoGN** [alexandrearaujo/modulo#64]
É interessante fazer o parse de datas do tipo DATE automático da view para o Spring. 
Hoje o parse automático só ocorre com Timestamp e está dando muito trabalho fazer isso de forma manual.

**Comment by alexandrearaujo** [comment]
resolvido com
```java
@JsonDeserialize(using = JsonDateDeserializer.class)
@JsonSerialize(using = JsonDateSerializer.class)
private LocalDate dataDevolucao;
```
